title: Slack Conversation Export Display

# Build settings
markdown: kramdown

exclude:
  - README.md
  - .DS_Store
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - .idea
  - .gitignore
  
# from https://github.com/avillafiorita/jekyll-datapage_gen
page_gen:
  - data: "conversations"
    template: "conversation"
    name: "id"
    dir: "conversation"